### ISSUE TITLE
実施日程一覧をもとに一週間前と一日後に通知がくるシステム

### ISSUE THREAD

**Issue by hidetomasuoka** [manma-co/google-apps#10]
ref #9 
自動送信システムを作るのはパッと思いつかない。。。
こっちだったらまだできそうｗ

**Comment by hidetomasuoka** [comment]
# 相談内容

## メール送付先
* メール送付先は担当者それともML？
## メール送付数
* まとめて or ひとり１件？

**Comment by n-hinae** [comment]
（1）メール送付先は担当者それともML？
MLです！

（２）メール送付数
MLに１件おくれたら嬉しいです＾＾

**Comment by hidetomasuoka** [comment]
（３）出力項目は、なにが必要だろう？
名前と日付ぐらいかな？

**Comment by n-hinae** [comment]
（３）出力項目（メール本文に書くべき内容）は、なにが必要だろう？
名前と日付ぐらいかな？

最低限、日付さえあれば大丈夫です！
名前ももし可能であればお願いしたいです。ありがとうございます！

**Comment by hidetomasuoka** [comment]
#16 作成済み
