### ISSUE TITLE
リマインド機能を作る

### ISSUE THREAD

**Issue by n-hinae** [manma-co/google-apps#9]
https://docs.google.com/spreadsheets/d/10HSD3wEkMjdm3i-sPGQpIve212ZZWWCwhLJN4p5e6Us/edit?usp=sharing
毎回、
・実施一週間前に当日概要（集合場所、集合時間、参加者の基本情報）
・実施一日後にお礼メール
を送っているのですが、チェックミスで遅れが発生したりしています。
そこで
・一週間前と一日後に勝手にメールが送られるシステム
もしくは
・実施日程一覧をもとに一週間前と一日後に通知がくるシステム
ができたら嬉しいのですが
何か方法はないでしょうか。

**Comment by hidetomasuoka** [comment]
https://chrome.google.com/webstore/detail/yet-another-mail-merge/mgmgmhkohaenhokbdnlpcljckbhpbmef?utm_source=permalink

余談だがこのアドオンはいつか使えるかもしれない

**Comment by hidetomasuoka** [comment]
#16 作成済み
